---

- name: Ensure sudo package installed and up to date
  apt:
    name: sudo
    state: present
  tags:
    - ssh
    - packages

- name: Ensure deploy group is present
  become: yes
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ deploy_group }}"
  when: install_deploy_user
  tags:
    - ssh

- name: Ensure deploy user is present
  become: yes
  user:
    name: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    create_home: no
    state: present
    shell: /bin/bash
  when: install_deploy_user
  tags:
    - ssh

- name: Add deploy user sudoers items for services
  become: yes
  template:
    src: deploy-sudoers.j2
    dest: "/etc/sudoers.d/{{ deploy_user }}-services"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
  when: install_deploy_user
  tags:
    - ssh

- include: users.yml
  when: users is defined
  tags:
    - users
    - ssh