---

- name: Ensure sudo package installed and up to date
  apt:
    name: sudo
    state: present
  tags:
  - ssh
  - packages
  - users

- name: Ensure filesystem group is present
  become: yes
  group:
    name: "{{ fs_group }}"
    state: present
  when: install_fs_user
  tags:
  - users

- name: Ensure filesystem user is present
  become: yes
  user:
    name: "{{ fs_user }}"
    group: "{{ fs_group }}"
    create_home: yes
    state: present
    shell: /bin/bash
  when: install_fs_user
  tags:
  - users

- name: Add filesystem user sudoers items for services
  become: yes
  template:
    src: deploy-sudoers.j2
    dest: "/etc/sudoers.d/{{ fs_user }}-services"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
  when: install_fs_user
  tags:
  - users

- include_tasks: users.yml
  when: users
  tags:
  - users